namePrefix: football-
commonLabels:
  infra: docker
resources:
- namespace.yaml
bases:
- ../../../base
namespace: football
patchesStrategicMerge:
- healthCheck.yaml
- cluster.yaml
- clusterClass.yaml
