apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  infra: docker

resources:
- cluster.yaml
- clusterClass.yaml
- dockerClusterTemplate.yaml
- dockerMachineTemplate.yaml
- kubeadmConfigTemplate.yaml
- kubeadmControlplaneTemplate.yaml
- healthCheck.yaml